spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/db_media_app
    username: postgres
    password: 123

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#para seguridad
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/user